import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0F1526',
        'on-primary-fixed': '#351000',
        'on-error': '#690005',
        'on-secondary': '#003642',
        'surface-container-high': '#252a38',
        'surface-variant': '#303443',
        'surface-container': '#1a1f2d',
        'on-secondary-fixed': '#001f27',
        'primary-fixed-dim': '#ffb693',
        'surface-bright': '#343948',
        'surface-tint': '#ffb693',
        'surface-dim': '#0e1320',
        'on-surface': '#dee2f5',
        'on-secondary-fixed-variant': '#004e5f',
        'primary-container': '#ff6b00',
        'on-tertiary-container': '#003357',
        'surface-container-low': '#161b29',
        'on-primary': '#561f00',
        'border-hover': 'rgba(255, 107, 0, 0.25)',
        'text-muted': 'rgba(255, 255, 255, 0.45)',
        'outline-variant': '#5a4136',
        'on-tertiary-fixed': '#001d35',
        'tertiary-fixed-dim': '#9ccaff',
        'error-container': '#93000a',
        outline: '#a98a7d',
        primary: '#ffb693',
        'inverse-primary': '#a04100',
        background: '#0e1320',
        'on-primary-container': '#572000',
        'surface-container-lowest': '#090e1b',
        'on-secondary-container': '#005669',
        'on-error-container': '#ffdad6',
        'tertiary-container': '#059eff',
        'on-surface-variant': '#e2bfb0',
        'secondary-fixed': '#b4ebff',
        'on-tertiary': '#003257',
        'inverse-on-surface': '#2b303e',
        'secondary-fixed-dim': '#3cd7ff',
        'inverse-surface': '#dee2f5',
        'on-primary-fixed-variant': '#7a3000',
        secondary: '#a2e7ff',
        'tertiary-fixed': '#d0e4ff',
        tertiary: '#9ccaff',
        'on-tertiary-fixed-variant': '#00497b',
        'surface-container-highest': '#303443',
        'primary-fixed': '#ffdbcc',
        'secondary-container': '#00d2fd',
        'border-default': 'rgba(255, 255, 255, 0.07)',
        'on-background': '#dee2f5',
        error: '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '24px',
        gutter: '24px',
        unit: '8px',
        'container-max': '1280px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'display-md': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1.0', letterSpacing: '2.5px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.5px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '1.0', letterSpacing: '-3px', fontWeight: '800' }],
        'display-md': ['56px', { lineHeight: '1.1', letterSpacing: '-2px', fontWeight: '800' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-1.5px', fontWeight: '800' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-1px', fontWeight: '800' }],
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        ticker: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        carousel: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        ticker: 'ticker 30s linear infinite',
        carousel: 'carousel 40s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
